### ISSUE TITLE
Use Kjua for QR Code

### ISSUE THREAD

**Issue by martinschilliger** [rsalzer/simple-qrbill#1]
Hi Robert

I really like your approach! Did you consider using [Kjua](https://github.com/lrsjng/kjua) for the QR Code? What do you think about adding some npm magic, and maybe also some frontend framework for the design of the page?

(wanted to ask before creating some pull request 🙃)

Martin

**Comment by rsalzer** [comment]
Hi Martin

Yes, I looked at some QR-Code-libraries. But then just used the simplest approach ...

Mainly because there are already some nice qr-bill-generators like this one: https://qr-rechnung.net/
So the "only" benefit would be to do it open source ;)
By "npm magic" you mean adding some useful js-libraries? ;)

And yes please: Proceed! :)

**Comment by martinschilliger** [comment]
Ah, the page in the link looks great! So I think I will use this site before re-inventing the wheel.
Yes I mainly thought about a frontend library and Kjua.
